trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install @antora/cli@2.0 @antora/site-generator-default@2.0
  displayName: 'Install Antora'

- script: |
    antora site.yml --stacktrace
  displayName: 'Generate Site'